version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.9.6
    commands:
      - echo "Installing dependencies..."
      - curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py
      - python3 get-pip.py
      - python3 -m pip install --upgrade pip
      - python3 -m pip install "flask>=3.0.0" "werkzeug>=3.0.0" "pytest" "pytest-cov"
      
  pre_build:
    commands:
      - echo "Running tests..."
      - python3 -m pytest test_app.py --cov=./ --cov-report=term-missing
      
  build:
    commands:
      - echo "Build started on `date`"
      - echo "Compiling the Python code..."
      - python3 -m py_compile web.py
      
  post_build:
    commands:
      - echo "Build completed on `date`"
artifacts:
  files:
    - web.py
    - requirements.txt
    - appspec.yml
    - templates/**/*
    - scripts/**/*
  discard-paths: no

cache:
  paths:
    - '/root/.cache/pip/**/*'
